[package]
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["command-line-utilities"]
description = "Just a blockchain implemented by me for fun"
edition = "2021"
homepage = "https://github.com/veeso/just-a-blockchain"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["networking"]
license = "The Unlicense"
name = "jab"
readme = "README.md"
repository = "https://github.com/veeso/just-a-blockchain"
version = "0.1.0"

[[bin]]
name = "jab"
path = "src/main.rs"

[dependencies]
argh = "0.1.7"
thiserror = "^1.0.0"

[dev-dependencies]
pretty_assertions = "^1.2.0"

[features]
default = []

[profile.dev]
incremental = true

[profile.release]
strip = true
